### ISSUE TITLE
Test screen reader capability for article.hosting

### ISSUE THREAD

**Issue by astrajescu** [hivereview/article-hosting#109]
Using Chrome browser extension, test the site assistive capability for the visually impaired.

**Comment by gaenache** [comment]
[screen reader.zip](https://github.com/hivereview/article-hosting/files/5444771/screen.reader.zip)

**Comment by gaenache** [comment]
- See attached Test Evidence for Screen Reader.
[Test Evidence(Screen Reader).zip](https://github.com/hivereview/article-hosting/files/5444833/Test.Evidence.Screen.Reader.zip)
We used for testing extension Screen Reader for Google Chrome.
Browser Chrome Version 86.0.4240.111
https://chrome.google.com/webstore/detail/screen-reader-for-google/nddfhonnmhcldcbmhbdldfpkbfpgjoeh?hl=en

- See attached Accessibility Report:
[article.hostig Report.html.zip](https://github.com/hivereview/article-hosting/files/5445384/article.hostig.Report.html.zip)
