### ISSUE TITLE
Implement xml conversion for bioRxiv original articles

### ISSUE THREAD

**Issue by magrigor** [hivereview/article-hosting#110]
List of elements which should be replaced on original bioRxiv articles based on conversation with Fred:

1. replace all  html chars to special chars
2. article xml doctype header?
3. replace ```<subj-group subj-group-type="hwp-journal-call"``` to ```<subj-group subj-group-type="subject"```
4. replace all ```<xref ref-type="corresp"``` to ```<xref ref-type="fn"```. Whole xml or only under ```<contrib``` element? 
5. replace ```<corresp``` to ```<fn```, place whole content under ```<p``` and remove other html tags
6. replace ```<kwd-group kwd-group-type="author"``` to ```<kwd-group kwd-group-type="author-generated"```
7. replace
```xml
<table-wrap id="utbl2" orientation="portrait" position="float">
   <graphic xlink:href="905919v1_utbl2a.tif"/>
   <graphic xlink:href="905919v1_utbl2b.tif"/>
</table-wrap>
```
to
```xml
<fig id="fig1" position="float">
  <label>Figure 1.</label>
  <graphic xlink:href="ijm-00196-fig1.tif" mimetype="image" mime-subtype="tiff"/>
</fig>
```
note: 
 - [stencila/encoda](https://github.com/stencila/encoda) don't recognize table with images, so we should map all table-wrap from bioRxiv as figures, otherwise receiving plain tables
 - should generate sample label if not exists? Example: for frst figure generate "Figure 1.", scnd "Figure 2." etc.
8. into ref-list.ref.* replace all ```<mixed-citation``` to ```<element-citation```, inside replace:
 - wrap each ```<ref``` item with ```<person-group person-group-type="author"``` ref.element-citation.person-group.name level
 - remove spaces between tags
 - replace ```<string-name``` to ```<name```

**Comment by fred-atherden** [comment]
> article xml doctype header?

Fine to leave this as is.

> replace all `<xref ref-type="corresp"` to `<xref ref-type="fn"`. Whole xml or only under `<contrib` element?

Whole XML would be safer. But it _should_ only appear under the `<contrib>` (unless there are problems with the XML which is unfortunately a possibility).

> should generate sample label if not exists? Example: for frst figure generate "Figure 1.", scnd "Figure 2." etc.

I would use the `<label>` from the `<table-wrap>` element. If there isn't one, then the `<fig>` can be without one (a label shouldn't be required).

## Additions
All outlined in [this XSL](https://github.com/hivereview/article-hosting/files/5480922/biorxiv2hive.xsl.zip) if that's easier to discern. 

1. Also need to move `<label>` in `<sec>` to the start of the `<title>`. If there is no `<title>` for the sec (this is very unlikely), then the `<label>` should simply be changed to `<title>`.

2. The same `<label>` issue ☝️ needs to be handled in the same way for `<app>`s.

3. `<sec>`s in `<abstract>`s need to be changed to `<p>`s.

4. Change any `<uri>` to `<ext-link ext-link-type="uri" xlink:href="{$uri}">{$uri}</ext-link>` (where `{$uri}` is the text contained in `<uri>`).

5. Any `<fig>` or `<table-wrap>` with more than 1 `<graphic>` should be turned into multiple `<fig>`s - one for each `<graphic>`. The `<label>` of the original can be used for the first, and subsequent ones can be without a `<label>`.

6. Same solution as 5 above ☝️ for `<supplementary-material>` with multiple `<media>`s.

7. `<inline-formula>` and `<disp-formula>` - bioRxiv capture them like this:
```xml
<disp-formula id="eqn1">
<alternatives><graphic xlink:href="000026_eqn1.gif"/></alternatives>
</disp-formula>
```

We need to get rid of the `<alternatives>` so it looks like this:
```xml
<disp-formula id="eqn1">
<graphic xlink:href="000026_eqn1.gif"/>
</disp-formula>
```

I'm also unsure how Encoda will deal with formula that have images - may need exploring...

**Comment by magrigor** [comment]
@FAtherden-eLife  Awesome, thank you very much!
