### ISSUE TITLE
Initial setup of testing framework

### ISSUE THREAD

**Issue by astrajescu** [hivereview/article-hosting#2]
**Rationale:** current [https://github.com/libero/prc](libero/prc) doesn't cover End to End (E2E) test cases which should validate the web app integrity from end user perspective, which results in a risk to not detect bugs in web app, & would require manual testing as compensation (which at the end would impact the team velocity)

**Task breakdown:**
- **Implement Page object model (PoM)**
   **impact of not having:** non linear maintenance effort to support automated tests & low readability of automated test code
   **benefit:** ensure re-usability of page element locators & results in linear maintenance effort in case of changes in app under test
   **example:** https://github.com/amiya-pattnaik/webdriverIO-with-cucumberBDD/blob/master/test/pageobjects/yahoo-search.page.js

- **Add webdriver.io as web browser connector**
   **impact of not having:** vanilla selenium-webdriver requires additional effort to implement reporting, management layer for different browser support & selenium wrapper functions which require
   **benefit:** webdriver.io is wrapper for selenium-webdriver, which minimizes boilerplate for page element location, includes ready to use reporting plugins (Slack, Jenkins) & utility services (browserstack), includes built in capability to rerun flaky tests.
   **example:** https://webdriver.io/

- driver management (support chrome, firefox or browserstack remote driver)
  **benefit:** ensure target browser change via config parameters, which enables cross-browser testing later on

- **Add implicit screenshot & action evidence reporting**
   **benefit: minimize effort for evidence collection in test step implementation**

CC: Hi @BlueReZZ , please, reply if you have any questions regarding above mentioned test framework features, so far we believe this is the way to go in order to minimize effort & increase velocity on PRC Article Hosting project.

**Comment by BlueReZZ** [comment]
This looks like a good direction for the end to end tests. The `prc` repo will have similar at some point but the team have not prioritised it yet. The Page Object Model is something we've used in the past, as is webdriver so a good choice for us. One of our developers is moving from an older project to The Hive in the next few weeks and will be working on end to end tests for that. His previous work is in https://github.com/libero/reviewer-client/tree/master/tests and you can see that the tooling and approach is similar to this proposal.
