### ISSUE TITLE
Receive a hand-made Hive article

### ISSUE THREAD

**Issue by astrajescu** [hivereview/article-hosting#3]
Receive one single hand-made Hive article as a starting point material.

**Comment by astrajescu** [comment]
We'll use IJM XML file for a start as it is simple and already worked with it. However, we'll receive shortly some samples of new XMLs from Fred and we'll work with them as well.

**Comment by BlueReZZ** [comment]
@astrajescu I've spoken to @FAtherden-eLife who will create a Hive XML version of an IJM article for us - one that features figures, tables etc. so that we have a reasonably complete view of the data we need to parse and map.

**Comment by astrajescu** [comment]
> @astrajescu I've spoken to @FAtherden-eLife who will create a Hive XML version of an IJM article for us - one that features figures, tables etc. so that we have a reasonably complete view of the data we need to parse and map.

It would be best to use a Research article - as it is most common, more complex, bigger and has pictures and tables, for example article #00196

**Comment by fred-atherden** [comment]
@BlueReZZ, @astrajescu  Hive version of an IJM article attached. Let me know if you have any questions. 
[ijm-00202.zip](https://github.com/hivereview/article-hosting/files/4981805/ijm-00202.zip)
