### ISSUE TITLE
Setup nginx ingress controller for article-hosting kubernetes cluster

### ISSUE THREAD

**Issue by SidhNor** [hivereview/article-hosting#42]
An ingress controller setup is required to properly redirect from http to https as well as route to different kubernetes services within the cluster.

The standard kubernetes nginx ingress should be used

**Comment by erkannt** [comment]
Feel free to copy the values we use in our eLife k8s cluster. Currently the ELB handles SSL termination. Going to change this soon to the ingress handling termination to allow for HTTP/2

https://github.com/elifesciences/elife-flux-cluster/blob/master/system/infra/ingress-nginx-controller.yaml

**Comment by erkannt** [comment]
Implemented local SSL termination and HTTP/2 yesterday.
