### ISSUE TITLE
Create S3 bucket to receive bundle content from Exeter

### ISSUE THREAD

**Issue by astrajescu** [hivereview/article-hosting#54]
In order to receive bundle content from Exeter Premedia (IJM articles) we need to create a S3 bucket for uploading files and grant access to the publisher. As part of automation process, uploading of articles will call to AWS SQS service.

**Comment by rtudvasev** [comment]
Added in https://github.com/hivereview/article-hosting-infrastructure/commit/0691a706ed35198b9713c652d6dece8a3b197bab
