### ISSUE TITLE
(Investigate) Clear SQS events

### ISSUE THREAD

**Issue by astrajescu** [hivereview/article-hosting#65]
Investigate if removing/cleaning of SQS generated events is necessary.

**Comment by rtudvasev** [comment]
AWS SDK doesn`t remove message from SQS after it was received. Call to delete message is required.
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sqs-examples-send-receive-messages.html#sqs-examples-send-receive-messages-receiving
