### ISSUE TITLE
Send email message for fail scenario

### ISSUE THREAD

**Issue by astrajescu** [hivereview/article-hosting#66]
When automated processing of content is completed by lambda function, a notification should be generated (Slack, email).

UPD: Send email with necessary context on each article import failed and place the zip to specific bucket

**Comment by magrigor** [comment]
From discussion, at the begging will be using only email notification for processed with fail articles

**Comment by magrigor** [comment]
Adding to AWS  infrastructure SES (Simple Email Service)
